# Generated by Django 5.0.1 on 2024-01-30 16:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variants', models.JSONField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2024, 1, 31, 2, 24, 36, 365869))),
                ('finish_date', models.DateTimeField(default=datetime.datetime(2024, 1, 31, 2, 24, 36, 365869))),
                ('participation_percentage', models.PositiveIntegerField(default=0)),
                ('allowed_users', models.ManyToManyField(related_name='allowed_votings', to='voting.users')),
            ],
        ),
        migrations.CreateModel(
            name='VotingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_code', models.TextField(max_length=10, unique=True)),
                ('chosen', models.TextField()),
                ('is_entered', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.users')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voting')),
            ],
        ),
        migrations.CreateModel(
            name='SendResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('voting_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votingprocess')),
            ],
        ),
    ]
