# Generated by Django 5.0.1 on 2024-01-31 06:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_voting_is_secret_votingprocess_is_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 16, 16, 2, 180995)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 16, 16, 2, 180995)),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.voting')),
            ],
        ),
    ]
