# Generated by Django 5.0.1 on 2024-01-31 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_voting_finish_date_alter_voting_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='variants',
        ),
        migrations.AlterField(
            model_name='voting',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 16, 41, 53, 841655)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 16, 41, 53, 841655)),
        ),
    ]
