# Generated by Django 5.0.1 on 2024-01-31 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_voting_variants_alter_voting_finish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingprocess',
            name='is_secret',
        ),
        migrations.AlterField(
            model_name='voting',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 18, 36, 30, 357042)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 18, 36, 30, 357042)),
        ),
    ]
