# Generated by Django 5.0.1 on 2024-01-31 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_voting_finish_date_alter_voting_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 19, 4, 23, 917941)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 19, 4, 23, 917941)),
        ),
    ]
