# Generated by Django 5.0.1 on 2024-01-31 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_voting_finish_date_alter_voting_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 20, 25, 32, 605376)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 20, 25, 32, 605376)),
        ),
        migrations.AlterField(
            model_name='votingprocess',
            name='chosen',
            field=models.TextField(default='-'),
        ),
        migrations.DeleteModel(
            name='SendResults',
        ),
    ]
