# Generated by Django 5.0.1 on 2024-01-31 15:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_voting_finish_date_alter_voting_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 1, 57, 46, 396346)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 1, 57, 46, 396346)),
        ),
        migrations.CreateModel(
            name='SendResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('voting_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votingprocess')),
            ],
        ),
    ]
